import {describe,it,expect} from 'vitest';
import * as T from 'three';
import {cleanGarmentFit,garmentTransform,deformGarment,manualCoverage} from '../apps/room3d/chibi/garmentFit';
const box=new T.Box3(new T.Vector3(-1.4,2.3,-.3),new T.Vector3(1.4,3.4,.3));
describe('per-garment rest-space fitting',()=>{
 it('defaults preserve authored positions and normals',()=>{const g=new T.BoxGeometry(.8,1,.4);g.translate(0,2.8,0);const p=Array.from(g.attributes.position.array),n=Array.from(g.attributes.normal.array);deformGarment(g,garmentTransform('top',cleanGarmentFit(),1,box));Array.from(g.attributes.position.array).forEach((v,i)=>expect(v).toBeCloseTo(p[i],6));Array.from(g.attributes.normal.array).forEach((v,i)=>expect(v).toBeCloseTo(n[i],6));});
 it('sleeve length extends arms symmetrically without moving the neckline; lower length anchors waist',()=>{const top=garmentTransform('top',cleanGarmentFit({sleeveLength:120}),1,box);expect(top(new T.Vector3(.1,3.3,0)).x).toBeCloseTo(.1);expect(top(new T.Vector3(1,3.125,0)).x).toBeCloseTo(1.14);expect(top(new T.Vector3(-1,3.125,0)).x).toBeCloseTo(-1.14);const bottom=garmentTransform('bottom',cleanGarmentFit({length:130}),1,box);expect(bottom(new T.Vector3(0,box.max.y,0)).y).toBe(box.max.y);expect(bottom(new T.Vector3(0,box.min.y,0)).y).toBeLessThan(box.min.y);});
 it('rejects invalid stored values and leaves unselected skin regions visible',()=>{const fit=cleanGarmentFit({width:Infinity,depth:800,offsetY:NaN,hide:['torso','bogus'] as never});expect(fit.width).toBe(100);expect(fit.depth).toBe(150);expect(fit.offsetY).toBe(0);expect(fit.hide).toEqual(['torso']);expect(manualCoverage(new T.Vector3(0,2.8,0),fit.hide,1)).toBe(true);expect(manualCoverage(new T.Vector3(1.5,3.1,0),fit.hide,1)).toBe(false);});
 it('sleeve ease accepts inward values and leaves the torso unchanged',()=>{const fit=cleanGarmentFit({clearance:0,sleeveClearance:-4}),transform=garmentTransform('top',fit,1,box),torso=new T.Vector3(.1,2.8,.2),sleeve=new T.Vector3(1,3.325,-.0106);expect(transform(torso.clone()).distanceTo(torso)).toBeLessThan(1e-6);expect(transform(sleeve.clone()).y).toBeCloseTo(sleeve.y-.04);const bodyOnly=garmentTransform('top',cleanGarmentFit({clearance:4,sleeveClearance:0}),1,box);expect(bodyOnly(sleeve.clone()).distanceTo(sleeve)).toBeLessThan(1e-6);expect(cleanGarmentFit({clearance:3}).sleeveClearance).toBe(3);expect(cleanGarmentFit({clearance:-3}).clearance).toBe(-3);});
 it('positions and rotates headwear around its own center',()=>{const headBox=new T.Box3(new T.Vector3(.1,4.4,-.1),new T.Vector3(.5,4.6,.1)),center=headBox.getCenter(new T.Vector3()),p=center.clone().add(new T.Vector3(.2,0,0));const transform=garmentTransform('headwear',cleanGarmentFit({rotateZ:90,offsetX:-10,offsetY:5,offsetZ:-8}),1,headBox);expect(transform(p).distanceTo(center.clone().add(new T.Vector3(-.1,.25,-.08)))).toBeLessThan(1e-6);});
});
