import {describe,it,expect} from 'vitest';import fs from 'node:fs';
import catalog from '../public/room3d/catalog.json';import {bathroomHome} from '../test/fixtures/bathroom-layout.js';
import {placementError,validateHome,moveFurniture} from '../apps/room3d/model.js';import {roomSeats} from '../apps/room3d/seating.js';
import {furniturePaintMaterials,validFurnitureColor} from '../apps/room3d/furniturePaint.js';
const read=(path:string)=>{const b=fs.readFileSync(path);return JSON.parse(b.subarray(20,20+b.readUInt32LE(12)).toString());};
function materials(j:any,i:number,result=new Set<string>()):string[]{const n=j.nodes[i];if(n.mesh!==undefined)for(const p of j.meshes[n.mesh].primitives)result.add(j.materials[p.material].name);for(const c of n.children||[])materials(j,c,result);return [...result];}
describe('bathroom furniture and catalog paint contracts',()=>{
 it('has real paintable surfaces for every shipped furniture, retaining secondary materials',()=>{const kit=read('public/room3d/kit.glb');for(const a of catalog.filter(a=>a.id!=='shell')){const names=a.url?read('public/room3d/'+a.url).materials.map((m:any)=>m.name):materials(kit,kit.nodes.findIndex((n:any)=>n.extras?.assetId===a.id));expect(a.paintMaterials?.length,a.id).toBeGreaterThan(0);expect(a.paintMaterials?.every((n:string)=>names.includes(n)),a.id).toBe(true);expect(furniturePaintMaterials(a,names),a.id).toEqual(a.paintMaterials);}});
 it('recovers a missing material mapping and restricts custom color input',()=>{expect(furniturePaintMaterials({paintMaterials:['absent']},['woodLight','brass'])).toEqual(['woodLight']);expect(validFurnitureColor('#123abc')).toBe(true);expect(validFurnitureColor('url(unsafe)')).toBe(false);expect(validFurnitureColor('#123')).toBe(false);});
 it('splits 15 pieces, preserves nested supports and has one reviewed stool seat',()=>{const h=bathroomHome(catalog),r=h.rooms[0];expect(r.items).toHaveLength(15);expect(r.items.map(i=>[i.id,placementError(i,r,catalog)]).filter(v=>v[1])).toEqual([]);expect(validateHome(h,catalog).rooms).toEqual(h.rooms);expect(roomSeats(r,catalog)).toHaveLength(1);expect(r.items.find(i=>i.id==='bath_soap').supportId).toBe('bath_tray');expect(r.items.find(i=>i.id==='bath_tray').supportId).toBe('bath_tub');});
 it('moves and rotates the tub with its board and soap, preserving colors',()=>{const h=bathroomHome(catalog),r=h.rooms[0];r.items=r.items.filter(i=>['bath_tub','bath_tray','bath_soap'].includes(i.id));r.items[0].color='#aabbcc';for(const rotation of [90,180,270,0]){moveFurniture(r,'bath_tub',{x:0,z:0,rotation},catalog);expect(r.items.map(i=>placementError(i,r,catalog))).toEqual(['','','']);expect(r.items[0].color).toBe('#aabbcc');}});
});
